#!/bin/bash
# NEXTFLOW TASK: bwa_map (1)
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 2 ]] && set -x

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a ALL_CHILD
    while read P PP;do
        ALL_CHILD[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    walk() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${ALL_CHILD[$1]:=}; do walk $i; done
    }

    walk $1
}

function nxf_mktemp() {
    local base=${1:-/tmp}
    [[ $(uname) = Darwin ]] && mktemp -d $base/nxf.XXXXXXXXXX || mktemp -d -t nxf.XXXXXXXXXX -p $base
}

on_exit() {
  exit_status=${ret:=$?}
  printf $exit_status > /vagrant/bioinformatics-workflows/nextflow/work/1b/e7e4a0e5bfb5cd16abc1cfa2c7dd12/.exitcode
  rm -f "$COUT" || true
  rm -f "$CERR" || true
  exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && nxf_kill $pid
}

trap on_exit EXIT
trap on_term TERM INT USR1 USR2

[[ $NXF_DEBUG > 0 ]] && nxf_env
touch /vagrant/bioinformatics-workflows/nextflow/work/1b/e7e4a0e5bfb5cd16abc1cfa2c7dd12/.command.begin
[ -f /vagrant/bioinformatics-workflows/nextflow/work/1b/e7e4a0e5bfb5cd16abc1cfa2c7dd12/.command.env ] && source /vagrant/bioinformatics-workflows/nextflow/work/1b/e7e4a0e5bfb5cd16abc1cfa2c7dd12/.command.env
rm -f genome.fa
rm -f A.fastq
ln -s /vagrant/bioinformatics-workflows/nextflow/data/genome.fa genome.fa
ln -s /vagrant/bioinformatics-workflows/nextflow/data/samples/A.fastq A.fastq


set +e
COUT=$PWD/.command.po; mkfifo "$COUT"
CERR=$PWD/.command.pe; mkfifo "$CERR"
tee .command.out < "$COUT" &
tee1=$!
tee .command.err < "$CERR" >&2 &
tee2=$!
(
/bin/bash -ue /vagrant/bioinformatics-workflows/nextflow/work/1b/e7e4a0e5bfb5cd16abc1cfa2c7dd12/.command.sh
) >"$COUT" 2>"$CERR" &
pid=$!
wait $pid || ret=$?
wait $tee1 $tee2
